name: ci
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint:fix

      - name: Format
        run: yarn format:write && yarn format:check

      - name: Type Check
        run: yarn type-check

      - name: Test
        run: yarn test:coverage

      - name: Build
        run: yarn build
